public class workFlowTest {
    public void workFlowTest(){
       System.debug('This apex class to test github action workflow'); 
       // Step 1 change
       System.debug('This apex class to test github action workflow1'); 
        //Step 2 change
        System.debug('This apex class to test github action workflow2'); 
        //Step 3 change
        System.debug('This apex class to test github action workflow3'); 
        //Step 4 change
        System.debug('This apex class to test github action workflow4');
        //Step 5 change
        System.debug('This apex class to test github action workflow5');
         //Step 6 change
        System.debug('This apex class to test github action workflow6');
        //Step 7 change
        System.debug('This apex class to test github action workflow7');
        //Step 8 change
        System.debug('This apex class to test github action workflow8');
    
    }
}