public class workFlowTest {
    public void workFlowTest(){
       System.debug('This apex class to test github action workflow'); 
       // Step 1 change
       System.debug('This apex class to test github action workflow1'); 
        //Step 2 change
        System.debug('This apex class to test github action workflow2'); 
        //Step 3 change
        System.debug('This apex class to test github action workflow3'); 
        //Step 4 change
        System.debug('This apex class to test github action workflow4'); 
        //Step 5 change
        System.debug('This apex class to test github action workflow5'); 
    }
}