name: Deploy to Salesforce Environments on Push to Main

on:
  push:
    branches: [ main ]
    paths:
      - 'force-app/**'

jobs:
  Deploy-to-Salesforce:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 2: Checkout source code
      - name: 'Checkout source code'
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'

      # Step 3: Install Salesforce CLI
      - name: 'Install Salesforce CLI'
        run: npm install @salesforce/cli --global

      # Step 4: Authenticate to Dev1 and retrieve metadata
      - name: Authenticate to Dev1 and retrieve metadata
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.DEV1_USERNAME }} --jwt-key-file server.key --client-id ${{ secrets.DEV1_CLIENT_ID }} --instance-url https://test.salesforce.com --set-default
          sf project retrieve start --source-dir force-app
          echo "[INFO] Metadata retrieved from Dev1"

      # Step 5: Deploy the rk_test__c object to Test1
      - name: Deploy rk_test__c object to Test1
        run: |
          echo "${{ secrets.JWT_SERVER_KEY }}" > server.key
          sf org login jwt --username ${{ secrets.TEST1_USERNAME }} --jwt-key-file server.key --client-id ${{ secrets.TEST1_CLIENT_ID }} --instance-url https://test.salesforce.com --set-default
          sf project deploy start --source-dir force-app/main/default/objects/rk_test__c --test-level NoTestRun
          echo "[INFO] rk_test__c object deployed to Test1"

      # Step 6: Deploy remaining metadata to Test1
      - name: Deploy remaining metadata to Test1
        run: |
          sf project deploy start --source-dir force-app --test-level RunLocalTests
          echo "[INFO] Remaining metadata deployed to Test1"